edit .local/bin/connectvpn

diff --git a/.local/bin/connectvpn b/.local/bin/connectvpn
--- a/.local/bin/connectvpn
+++ b/.local/bin/connectvpn
@@ -5,7 +5,10 @@ if [ "$(id -u)" -ne 0 ]; then
   exit 1
 fi
 
+command -v curl > /dev/null 2>&1 || { echo >&2 "I require curl but it's not installed. Install it. Aborting."; exit 1; }
 command -v openvpn > /dev/null 2>&1 || { echo >&2 "I require openvpn but it's not installed. Install it. Aborting."; exit 1; }
+command -v unzip > /dev/null 2>&1 || { echo >&2 "I require unzip but it's not installed. Install it. Aborting."; exit 1; }
+command -v wget > /dev/null 2>&1 || { echo >&2 "I require wget but it's not installed. Install it. Aborting."; exit 1; }
 
 start() {
 cd /tmp
