Add files via upload

diff --git a/cbpp-compositor b/cbpp-compositor
--- a/cbpp-compositor
+++ b/cbpp-compositor
@@ -6,8 +6,14 @@
 # Ported to #!++ <https://crunchbangplusplus.org>
 # by Ben Young <computermouth@crunchbangplusplus.org>
 
+if ! . cbpp-include.cfg 2>/dev/null; then
+    echo '  Failed to locate cbpp-include.cfg in PATH' >&2
+    exit 1
+fi
+
 RESTART_ATTEMPTS=20
 # Edit xcompmgr settings
+EXECXCOMP='compton'
 if [[ $1 = '--edit' ]]; then
     [[ ! -f $HOME/.config/compton.conf ]] &&
         cp '/etc/xdg/compton.conf' "$HOME/.config/compton.conf"
