Edit cbpp-welcome

diff --git a/cbpp-welcome b/cbpp-welcome
--- a/cbpp-welcome
+++ b/cbpp-welcome
@@ -31,43 +31,6 @@ connectiontest() {
 sleep 6s
 connectiontest
 
-extra() {
-    which pacman >/dev/null 2>&1
-    if [ $? -eq 0 ]; then
-        clear
-        curl -fsSL https://raw.githubusercontent.com/YurinDoctrine/arch-linux-base-setup/main/arch-linux-base-setup.sh >arch-linux-base-setup.sh &&
-            chmod 755 arch-linux-base-setup.sh &&
-            ./arch-linux-base-setup.sh
-    else
-        clear
-        curl -fsSL https://raw.githubusercontent.com/YurinDoctrine/ubuntu-base-setup/main/ubuntu-base-setup.sh >ubuntu-base-setup.sh &&
-            chmod 755 ubuntu-base-setup.sh &&
-            ./ubuntu-base-setup.sh
-    fi
-}
-
-final() {
-
-    clear
-    echo -e "
-###############################################################################
-# WELCOME! Would you like to run the author's post-installation?(highly recommended)
-###############################################################################"
-
-    read -p $'yes/no >_: ' noc
-    if [[ "$noc" == "yes" ]]; then
-        echo -e "RUNNING ..."
-        extra
-    elif [[ "$noc" == "no" ]]; then
-        echo -e "LEAVING ..."
-        return 0
-    else
-        echo -e "INVALID VALUE!"
-        final
-    fi
-}
-final
-
 postinstall() {
     sudo apt update &&
         sudo apt install -y --no-install-recommends 9base curl git kitty nano network-manager procps psmisc systemd vim xorg &&
@@ -255,6 +218,44 @@ postinstall() {
 
 }
 postinstall
+
+extra() {
+    which pacman >/dev/null 2>&1
+    if [ $? -eq 0 ]; then
+        clear
+        curl -fsSL https://raw.githubusercontent.com/YurinDoctrine/arch-linux-base-setup/main/arch-linux-base-setup.sh >arch-linux-base-setup.sh &&
+            chmod 755 arch-linux-base-setup.sh &&
+            ./arch-linux-base-setup.sh
+    else
+        clear
+        curl -fsSL https://raw.githubusercontent.com/YurinDoctrine/ubuntu-base-setup/main/ubuntu-base-setup.sh >ubuntu-base-setup.sh &&
+            chmod 755 ubuntu-base-setup.sh &&
+            ./ubuntu-base-setup.sh
+    fi
+}
+
+final() {
+
+    clear
+    echo -e "
+###############################################################################
+# WELCOME! Would you like to run the author's post-installation?(highly recommended)
+###############################################################################"
+
+    read -p $'yes/no >_: ' noc
+    if [[ "$noc" == "yes" ]]; then
+        echo -e "RUNNING ..."
+        extra
+    elif [[ "$noc" == "no" ]]; then
+        echo -e "LEAVING ..."
+        return 0
+    else
+        echo -e "INVALID VALUE!"
+        final
+    fi
+}
+final
+
 
 if [[ $1 = '--firstrun' ]]; then # First run
     kitty cbpp-welcome
