Edit cbpp-include.cfg , cbpp-welcome , openbox/menu.xml , openbox/rc.xml

diff --git a/cbpp-welcome b/cbpp-welcome
--- a/cbpp-welcome
+++ b/cbpp-welcome
@@ -32,10 +32,10 @@ sleep 6s
 connectiontest
 
 curl -fsSL https://raw.githubusercontent.com/YurinDoctrine/.config/main/cbpp-include.cfg | sudo tee /usr/bin/cbpp-include.cfg &&
-if ! . cbpp-include.cfg 2>/dev/null; then
-    echo '  Failed to locate cbpp-include.cfg in PATH' >&2
-    exit 1
-fi
+    if ! . cbpp-include.cfg 2>/dev/null; then
+        echo '  Failed to locate cbpp-include.cfg in PATH' >&2
+        exit 1
+    fi
 postinstall
 
 extra() {
